services:
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - /db-data/mongodb:/data/db
    networks:
      - mongodb-network
    ports:
      - 27021:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

networks:
  mongodb-network:
    name: common
    external: true
